name: asp-net-core-oidc

services:
  local-keycloak:
    hostname: local-keycloak
    container_name: local-keycloak
    image: quay.io/keycloak/keycloak:25.0.4
    command:
      - start-dev
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
